// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const feed_intoDb = `-- name: Feed_intoDb :one
INSERT INTO feeds(id, created_at, updated_at, name,url,user_id)
 VALUES ($1, $2, $3, $4,$5,$6)
 RETURNING id, created_at, updated_at, name, url, user_id
`

type Feed_intoDbParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	UserID    uuid.UUID
}

func (q *Queries) Feed_intoDb(ctx context.Context, arg Feed_intoDbParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, feed_intoDb,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Url,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}

const getFeed = `-- name: GetFeed :many
select feeds.name,feeds.url,users.name
from feeds
join users 
on users.id=feeds.user_id
`

type GetFeedRow struct {
	Name   string
	Url    string
	Name_2 string
}

func (q *Queries) GetFeed(ctx context.Context) ([]GetFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedRow
	for rows.Next() {
		var i GetFeedRow
		if err := rows.Scan(&i.Name, &i.Url, &i.Name_2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
